#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:

        - image: #@ data.values.name
          command: [ /cnb/lifecycle/launcher ]
          env:
            - name: REDIS_ADDR
              value: "{{ .Inputs.serviceName }}:6379"
          name: app
