apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:d3159a7769f62ca629c5fb71208c3b6b061303e488062b637dc0be1cb0244f93
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: '{{ .Inputs.serviceName }}:6379'
        name: app
