apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:96f078da76e2a45e759a8ddb44f3c92a06c152affb24c9253bebe81bd8c9ab73
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: '{{ .Inputs.serviceName }}:6379'
        name: app
