apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:d5e55f43f322ad3531c3d136d61bfd4a3007d8d8244778efb58c21ecb18c4924
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: 'redis:6379'
        name: app
