apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:192f8de2eafbd77bf86e32f55fbb67b96aa8eaf970216b09fa472560c01541bc
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: '{{ .Inputs.serviceName }}:6379'
        name: app
