apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:00bfe05223f0fdb3015af50e581c92571f0f112ec8e82d35c48cccd7d34c3da6
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: '{{ .Inputs.serviceName }}:6379'
        name: app
