apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:fd2b65b82b5405f66ed01bffa74621bcc279b6e4ddd85ac338c742645d8e4ea2
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: redis:6379
        name: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app
  name: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: app
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmware-restrictired-psp-use
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - vmware-system-restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kontinue-manager-psp
roleRef:
  kind: ClusterRole
  name: vmware-restrictired-psp-use
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: demo-app
