apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: harbor-repo.vmware.com/tanzu_delivery_pipeline_demo/demo-app@sha256:03da78fd71ec16c15493a4bbbc2a8a7afede51e84cd117266937155fc506e40c
        command:
        - /cnb/lifecycle/launcher
        env:
        - name: REDIS_ADDR
          value: '{{ .Inputs.serviceName }}:6379'
        name: app
