#@ load("@ytt:data", "data")
---

apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:

        - image: #@ data.values.name
          command: [ /cnb/lifecycle/launcher ]
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
          name: app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app
  name: app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: app
  type: ClusterIP
